In [1]:
# Import dependencies
import pandas as pd

### EXTRACT:
##### - Heart Disease dataset 
##### - Census Data Population Estimates (Age 18+)

In [2]:
# Read in csv and excel files into Pandas Dataframe
heart_disease_2022_df = pd.read_csv('data\heart_2022_no_nans.csv') 
census_data_2022_df = pd.read_excel('data/SCPRC-EST2022-18+POP.xlsx', header=None)

In [3]:
# View all columns of the heart disease dataset
pd.set_option('display.max_columns', 40) 
heart_disease_2022_df.head()

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,HadAngina,HadStroke,HadAsthma,HadSkinCancer,HadCOPD,HadDepressiveDisorder,HadKidneyDisease,HadArthritis,HadDiabetes,DeafOrHardOfHearing,BlindOrVisionDifficulty,DifficultyConcentrating,DifficultyWalking,DifficultyDressingBathing,DifficultyErrands,SmokerStatus,ECigaretteUsage,ChestScan,RaceEthnicityCategory,AgeCategory,HeightInMeters,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,Female,Very good,4.0,0.0,Within past year (anytime less than 12 months ...,Yes,9.0,None of them,No,No,No,No,No,No,No,No,Yes,No,No,No,No,No,No,No,Former smoker,Never used e-cigarettes in my entire life,No,"White only, Non-Hispanic",Age 65 to 69,1.60,71.67,27.99,No,No,Yes,Yes,"Yes, received Tdap",No,No
1,Alabama,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,Yes,6.0,None of them,No,No,No,No,No,No,No,No,Yes,Yes,No,No,No,No,No,No,Former smoker,Never used e-cigarettes in my entire life,No,"White only, Non-Hispanic",Age 70 to 74,1.78,95.25,30.13,No,No,Yes,Yes,"Yes, received tetanus shot but not sure what type",No,No
2,Alabama,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,No,8.0,"6 or more, but not all",No,No,No,No,No,No,No,No,Yes,No,No,Yes,No,Yes,No,No,Former smoker,Never used e-cigarettes in my entire life,Yes,"White only, Non-Hispanic",Age 75 to 79,1.85,108.86,31.66,Yes,No,No,Yes,"No, did not receive any tetanus shot in the pa...",No,Yes
3,Alabama,Female,Fair,5.0,0.0,Within past year (anytime less than 12 months ...,Yes,9.0,None of them,No,No,No,No,Yes,No,Yes,No,Yes,No,No,No,No,Yes,No,No,Never smoked,Never used e-cigarettes in my entire life,No,"White only, Non-Hispanic",Age 80 or older,1.70,90.72,31.32,No,No,Yes,Yes,"No, did not receive any tetanus shot in the pa...",No,Yes
4,Alabama,Female,Good,3.0,15.0,Within past year (anytime less than 12 months ...,Yes,5.0,1 to 5,No,No,No,No,No,No,No,No,Yes,No,No,No,No,No,No,No,Never smoked,Never used e-cigarettes in my entire life,No,"White only, Non-Hispanic",Age 80 or older,1.55,79.38,33.07,No,No,Yes,Yes,"No, did not receive any tetanus shot in the pa...",No,No

In [4]:

# Get a brief summary of the heart disease dataFrame
heart_disease_2022_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246022 entries, 0 to 246021
Data columns (total 40 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   State                      246022 non-null  object
 1   Sex                        246022 non-null  object
 2   GeneralHealth              246022 non-null  object
 3   PhysicalHealthDays         246022 non-null  float64
 4   MentalHealthDays           246022 non-null  float64
 5   LastCheckupTime            246022 non-null  object
 6   PhysicalActivities         246022 non-null  object
 7   SleepHours                 246022 non-null  float64
 8   RemovedTeeth               246022 non-null  object
 9   HadHeartAttack             246022 non-null  object
 10  HadAngina                  246022 non-null  object
 11  HadStroke                  246022 non-null  object
 12  HadAsthma                  246022 non-null  object
 13  HadSkinCancer              246022 non-null  object
 14  HadCOPD                    246022 non-null  object
 15  HadDepressiveDisorder      246022 non-null  object
 16  HadKidneyDisease           246022 non-null  object
 17  HadArthritis               246022 non-null  object
 18  HadDiabetes                246022 non-null  object
 19  DeafOrHardOfHearing        246022 non-null  object
 20  BlindOrVisionDifficulty    246022 non-null  object
 21  DifficultyConcentrating    246022 non-null  object
 22  DifficultyWalking          246022 non-null  object
 23  DifficultyDressingBathing  246022 non-null  object
 24  DifficultyErrands          246022 non-null  object
 25  SmokerStatus               246022 non-null  object
 26  ECigaretteUsage            246022 non-null  object
 27  ChestScan                  246022 non-null  object
 28  RaceEthnicityCategory      246022 non-null  object
 29  AgeCategory                246022 non-null  object
 30  HeightInMeters             246022 non-null  float64
 31  WeightInKilograms          246022 non-null  float64
 32  BMI                        246022 non-null  float64
 33  AlcoholDrinkers            246022 non-null  object
 34  HIVTesting                 246022 non-null  object
 35  FluVaxLast12               246022 non-null  object
 36  PneumoVaxEver              246022 non-null  object
 37  TetanusLast10Tdap          246022 non-null  object
 38  HighRiskLastYear           246022 non-null  object
 39  CovidPos                   246022 non-null  object
dtypes: float64(6), object(34)
memory usage: 75.1+ MB

In [5]:
# View the census data
census_data_2022_df.head(10)

,0,1,2,3
0,table with row headers in column A and column ...,NaN,NaN,NaN
1,Estimates of the Total Resident Population and...,NaN,NaN,NaN
2,Geographic Area,Total Resident\nPopulation,Resident Population Age 18\n Years and Older,NaN
3,NaN,NaN,Number,Percent
4,United States,333287557,260836730,78.3
5,Northeast,57040406,45544589,79.8
6,Midwest,68787595,53626659,78
7,South,128716192,100098310,77.8
8,West,78743364,61567172,78.2
9,.Alabama,5074296,3962734,78.1

In [6]:
# Get a brief summary of the census dataFrame
census_data_2022_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       65 non-null     object
 1   1       58 non-null     object
 2   2       59 non-null     object
 3   3       58 non-null     object
dtypes: object(4)
memory usage: 2.2+ KB

### TRANSFRORM:
##### Heart Disease dataset

In [7]:
# Make a copy of the heart disease indicators dataset
hd_df = heart_disease_2022_df.copy()
hd_df.head()

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,HadAngina,HadStroke,HadAsthma,HadSkinCancer,HadCOPD,HadDepressiveDisorder,HadKidneyDisease,HadArthritis,HadDiabetes,DeafOrHardOfHearing,BlindOrVisionDifficulty,DifficultyConcentrating,DifficultyWalking,DifficultyDressingBathing,DifficultyErrands,SmokerStatus,ECigaretteUsage,ChestScan,RaceEthnicityCategory,AgeCategory,HeightInMeters,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,Female,Very good,4.0,0.0,Within past year (anytime less than 12 months ...,Yes,9.0,None of them,No,No,No,No,No,No,No,No,Yes,No,No,No,No,No,No,No,Former smoker,Never used e-cigarettes in my entire life,No,"White only, Non-Hispanic",Age 65 to 69,1.60,71.67,27.99,No,No,Yes,Yes,"Yes, received Tdap",No,No
1,Alabama,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,Yes,6.0,None of them,No,No,No,No,No,No,No,No,Yes,Yes,No,No,No,No,No,No,Former smoker,Never used e-cigarettes in my entire life,No,"White only, Non-Hispanic",Age 70 to 74,1.78,95.25,30.13,No,No,Yes,Yes,"Yes, received tetanus shot but not sure what type",No,No
2,Alabama,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,No,8.0,"6 or more, but not all",No,No,No,No,No,No,No,No,Yes,No,No,Yes,No,Yes,No,No,Former smoker,Never used e-cigarettes in my entire life,Yes,"White only, Non-Hispanic",Age 75 to 79,1.85,108.86,31.66,Yes,No,No,Yes,"No, did not receive any tetanus shot in the pa...",No,Yes
3,Alabama,Female,Fair,5.0,0.0,Within past year (anytime less than 12 months ...,Yes,9.0,None of them,No,No,No,No,Yes,No,Yes,No,Yes,No,No,No,No,Yes,No,No,Never smoked,Never used e-cigarettes in my entire life,No,"White only, Non-Hispanic",Age 80 or older,1.70,90.72,31.32,No,No,Yes,Yes,"No, did not receive any tetanus shot in the pa...",No,Yes
4,Alabama,Female,Good,3.0,15.0,Within past year (anytime less than 12 months ...,Yes,5.0,1 to 5,No,No,No,No,No,No,No,No,Yes,No,No,No,No,No,No,No,Never smoked,Never used e-cigarettes in my entire life,No,"White only, Non-Hispanic",Age 80 or older,1.55,79.38,33.07,No,No,Yes,Yes,"No, did not receive any tetanus shot in the pa...",No,No

In [8]:
# Split the 'RaceEthnicityCategory' column on the comma into two columns
hd_df[['Race', 'Ethnicity']] = hd_df['RaceEthnicityCategory'].str.split(',', expand=True)
hd_df.head()

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,HadAngina,HadStroke,HadAsthma,HadSkinCancer,HadCOPD,HadDepressiveDisorder,HadKidneyDisease,HadArthritis,HadDiabetes,DeafOrHardOfHearing,...,DifficultyWalking,DifficultyDressingBathing,DifficultyErrands,SmokerStatus,ECigaretteUsage,ChestScan,RaceEthnicityCategory,AgeCategory,HeightInMeters,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos,Race,Ethnicity
0,Alabama,Female,Very good,4.0,0.0,Within past year (anytime less than 12 months ...,Yes,9.0,None of them,No,No,No,No,No,No,No,No,Yes,No,No,...,No,No,No,Former smoker,Never used e-cigarettes in my entire life,No,"White only, Non-Hispanic",Age 65 to 69,1.60,71.67,27.99,No,No,Yes,Yes,"Yes, received Tdap",No,No,White only,Non-Hispanic
1,Alabama,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,Yes,6.0,None of them,No,No,No,No,No,No,No,No,Yes,Yes,No,...,No,No,No,Former smoker,Never used e-cigarettes in my entire life,No,"White only, Non-Hispanic",Age 70 to 74,1.78,95.25,30.13,No,No,Yes,Yes,"Yes, received tetanus shot but not sure what type",No,No,White only,Non-Hispanic
2,Alabama,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,No,8.0,"6 or more, but not all",No,No,No,No,No,No,No,No,Yes,No,No,...,Yes,No,No,Former smoker,Never used e-cigarettes in my entire life,Yes,"White only, Non-Hispanic",Age 75 to 79,1.85,108.86,31.66,Yes,No,No,Yes,"No, did not receive any tetanus shot in the pa...",No,Yes,White only,Non-Hispanic
3,Alabama,Female,Fair,5.0,0.0,Within past year (anytime less than 12 months ...,Yes,9.0,None of them,No,No,No,No,Yes,No,Yes,No,Yes,No,No,...,Yes,No,No,Never smoked,Never used e-cigarettes in my entire life,No,"White only, Non-Hispanic",Age 80 or older,1.70,90.72,31.32,No,No,Yes,Yes,"No, did not receive any tetanus shot in the pa...",No,Yes,White only,Non-Hispanic
4,Alabama,Female,Good,3.0,15.0,Within past year (anytime less than 12 months ...,Yes,5.0,1 to 5,No,No,No,No,No,No,No,No,Yes,No,No,...,No,No,No,Never smoked,Never used e-cigarettes in my entire life,No,"White only, Non-Hispanic",Age 80 or older,1.55,79.38,33.07,No,No,Yes,Yes,"No, did not receive any tetanus shot in the pa...",No,No,White only,Non-Hispanic

In [9]:
# Drop the 'RaceEthnicityCategory' column
hd_df = hd_df.drop(columns=('RaceEthnicityCategory'))
hd_df.head()

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,HadAngina,HadStroke,HadAsthma,HadSkinCancer,HadCOPD,HadDepressiveDisorder,HadKidneyDisease,HadArthritis,HadDiabetes,DeafOrHardOfHearing,...,DifficultyConcentrating,DifficultyWalking,DifficultyDressingBathing,DifficultyErrands,SmokerStatus,ECigaretteUsage,ChestScan,AgeCategory,HeightInMeters,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos,Race,Ethnicity
0,Alabama,Female,Very good,4.0,0.0,Within past year (anytime less than 12 months ...,Yes,9.0,None of them,No,No,No,No,No,No,No,No,Yes,No,No,...,No,No,No,No,Former smoker,Never used e-cigarettes in my entire life,No,Age 65 to 69,1.60,71.67,27.99,No,No,Yes,Yes,"Yes, received Tdap",No,No,White only,Non-Hispanic
1,Alabama,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,Yes,6.0,None of them,No,No,No,No,No,No,No,No,Yes,Yes,No,...,No,No,No,No,Former smoker,Never used e-cigarettes in my entire life,No,Age 70 to 74,1.78,95.25,30.13,No,No,Yes,Yes,"Yes, received tetanus shot but not sure what type",No,No,White only,Non-Hispanic
2,Alabama,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,No,8.0,"6 or more, but not all",No,No,No,No,No,No,No,No,Yes,No,No,...,No,Yes,No,No,Former smoker,Never used e-cigarettes in my entire life,Yes,Age 75 to 79,1.85,108.86,31.66,Yes,No,No,Yes,"No, did not receive any tetanus shot in the pa...",No,Yes,White only,Non-Hispanic
3,Alabama,Female,Fair,5.0,0.0,Within past year (anytime less than 12 months ...,Yes,9.0,None of them,No,No,No,No,Yes,No,Yes,No,Yes,No,No,...,No,Yes,No,No,Never smoked,Never used e-cigarettes in my entire life,No,Age 80 or older,1.70,90.72,31.32,No,No,Yes,Yes,"No, did not receive any tetanus shot in the pa...",No,Yes,White only,Non-Hispanic
4,Alabama,Female,Good,3.0,15.0,Within past year (anytime less than 12 months ...,Yes,5.0,1 to 5,No,No,No,No,No,No,No,No,Yes,No,No,...,No,No,No,No,Never smoked,Never used e-cigarettes in my entire life,No,Age 80 or older,1.55,79.38,33.07,No,No,Yes,Yes,"No, did not receive any tetanus shot in the pa...",No,No,White only,Non-Hispanic

In [10]:
# Check the uniques vales in the State column
states = hd_df['State'].unique()
states

array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
       'Colorado', 'Connecticut', 'Delaware', 'District of Columbia',
       'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana',
       'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
       'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi',
       'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
       'New Jersey', 'New Mexico', 'New York', 'North Carolina',
       'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania',
       'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee',
       'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
       'West Virginia', 'Wisconsin', 'Wyoming', 'Guam', 'Puerto Rico',
       'Virgin Islands'], dtype=object)

In [11]:
# Dropping rows (to keep all states and the District of Columbia ONLY)
hd_df = hd_df[~hd_df['State'].isin(['Guam', 'Puerto Rico', 'Virgin Islands'])] #.reset_index(drop=True)
hd_df.head()

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,HadAngina,HadStroke,HadAsthma,HadSkinCancer,HadCOPD,HadDepressiveDisorder,HadKidneyDisease,HadArthritis,HadDiabetes,DeafOrHardOfHearing,...,DifficultyConcentrating,DifficultyWalking,DifficultyDressingBathing,DifficultyErrands,SmokerStatus,ECigaretteUsage,ChestScan,AgeCategory,HeightInMeters,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos,Race,Ethnicity
0,Alabama,Female,Very good,4.0,0.0,Within past year (anytime less than 12 months ...,Yes,9.0,None of them,No,No,No,No,No,No,No,No,Yes,No,No,...,No,No,No,No,Former smoker,Never used e-cigarettes in my entire life,No,Age 65 to 69,1.60,71.67,27.99,No,No,Yes,Yes,"Yes, received Tdap",No,No,White only,Non-Hispanic
1,Alabama,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,Yes,6.0,None of them,No,No,No,No,No,No,No,No,Yes,Yes,No,...,No,No,No,No,Former smoker,Never used e-cigarettes in my entire life,No,Age 70 to 74,1.78,95.25,30.13,No,No,Yes,Yes,"Yes, received tetanus shot but not sure what type",No,No,White only,Non-Hispanic
2,Alabama,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,No,8.0,"6 or more, but not all",No,No,No,No,No,No,No,No,Yes,No,No,...,No,Yes,No,No,Former smoker,Never used e-cigarettes in my entire life,Yes,Age 75 to 79,1.85,108.86,31.66,Yes,No,No,Yes,"No, did not receive any tetanus shot in the pa...",No,Yes,White only,Non-Hispanic
3,Alabama,Female,Fair,5.0,0.0,Within past year (anytime less than 12 months ...,Yes,9.0,None of them,No,No,No,No,Yes,No,Yes,No,Yes,No,No,...,No,Yes,No,No,Never smoked,Never used e-cigarettes in my entire life,No,Age 80 or older,1.70,90.72,31.32,No,No,Yes,Yes,"No, did not receive any tetanus shot in the pa...",No,Yes,White only,Non-Hispanic
4,Alabama,Female,Good,3.0,15.0,Within past year (anytime less than 12 months ...,Yes,5.0,1 to 5,No,No,No,No,No,No,No,No,Yes,No,No,...,No,No,No,No,Never smoked,Never used e-cigarettes in my entire life,No,Age 80 or older,1.55,79.38,33.07,No,No,Yes,Yes,"No, did not receive any tetanus shot in the pa...",No,No,White only,Non-Hispanic

In [12]:
# Confirm the regions were dropped
states = hd_df['State'].unique()
states

array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
       'Colorado', 'Connecticut', 'Delaware', 'District of Columbia',
       'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana',
       'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
       'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi',
       'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
       'New Jersey', 'New Mexico', 'New York', 'North Carolina',
       'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania',
       'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee',
       'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
       'West Virginia', 'Wisconsin', 'Wyoming'], dtype=object)

In [13]:
# Replacing the Yes/No values to 0/1
columns_to_replace = [
    'HadHeartAttack', 'HadAngina', 'HadStroke', 'HadAsthma', 'HadSkinCancer',
    'HadCOPD', 'HadDepressiveDisorder', 'HadKidneyDisease', 'HadArthritis',
    'HadDiabetes', 'DeafOrHardOfHearing', 'BlindOrVisionDifficulty',
    'DifficultyConcentrating', 'DifficultyWalking', 'DifficultyDressingBathing',
    'DifficultyErrands', 'AlcoholDrinkers', 'ChestScan', 'HIVTesting',
    'FluVaxLast12', 'PneumoVaxEver', 'HighRiskLastYear', 'CovidPos', 'PhysicalActivities'
]

# Replace values in specified columns
for column in columns_to_replace:
    hd_df[column] = hd_df[column].replace({'No': 0, 'Yes': 1})

hd_df.head()

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,HadAngina,HadStroke,HadAsthma,HadSkinCancer,HadCOPD,HadDepressiveDisorder,HadKidneyDisease,HadArthritis,HadDiabetes,DeafOrHardOfHearing,...,DifficultyConcentrating,DifficultyWalking,DifficultyDressingBathing,DifficultyErrands,SmokerStatus,ECigaretteUsage,ChestScan,AgeCategory,HeightInMeters,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos,Race,Ethnicity
0,Alabama,Female,Very good,4.0,0.0,Within past year (anytime less than 12 months ...,1,9.0,None of them,0,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,Former smoker,Never used e-cigarettes in my entire life,0,Age 65 to 69,1.60,71.67,27.99,0,0,1,1,"Yes, received Tdap",0,0,White only,Non-Hispanic
1,Alabama,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,1,6.0,None of them,0,0,0,0,0,0,0,0,1,1,0,...,0,0,0,0,Former smoker,Never used e-cigarettes in my entire life,0,Age 70 to 74,1.78,95.25,30.13,0,0,1,1,"Yes, received tetanus shot but not sure what type",0,0,White only,Non-Hispanic
2,Alabama,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,0,8.0,"6 or more, but not all",0,0,0,0,0,0,0,0,1,0,0,...,0,1,0,0,Former smoker,Never used e-cigarettes in my entire life,1,Age 75 to 79,1.85,108.86,31.66,1,0,0,1,"No, did not receive any tetanus shot in the pa...",0,1,White only,Non-Hispanic
3,Alabama,Female,Fair,5.0,0.0,Within past year (anytime less than 12 months ...,1,9.0,None of them,0,0,0,0,1,0,1,0,1,0,0,...,0,1,0,0,Never smoked,Never used e-cigarettes in my entire life,0,Age 80 or older,1.70,90.72,31.32,0,0,1,1,"No, did not receive any tetanus shot in the pa...",0,1,White only,Non-Hispanic
4,Alabama,Female,Good,3.0,15.0,Within past year (anytime less than 12 months ...,1,5.0,1 to 5,0,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,Never smoked,Never used e-cigarettes in my entire life,0,Age 80 or older,1.55,79.38,33.07,0,0,1,1,"No, did not receive any tetanus shot in the pa...",0,0,White only,Non-Hispanic

In [14]:
# Check the unique values of HadDiabetes column
hadDiabetes_values = hd_df['HadDiabetes'].unique()
hadDiabetes_values

array([0, 1, 'Yes, but only during pregnancy (female)',
       'No, pre-diabetes or borderline diabetes'], dtype=object)

In [15]:
# Check the unique values of CovidPos column
covidPos_values = hd_df['CovidPos'].unique()
covidPos_values

array([0, 1,
       'Tested positive using home test without a health professional'],
      dtype=object)

In [16]:
# Replacing the other values of the HadDiabetes and CovidPos columns to numeric values
hd_df['HadDiabetes'] = hd_df['HadDiabetes'].replace({'Yes, but only during pregnancy (female)': 3,
       'No, pre-diabetes or borderline diabetes': 4})
hd_df['CovidPos'] = hd_df['CovidPos'].replace({'Tested positive using home test without a health professional': 3})

In [17]:
convert_list = [
    'PhysicalHealthDays', 'MentalHealthDays', 'SleepHours', 'PhysicalActivities',
    'HadHeartAttack', 'HadAngina', 'HadStroke', 'HadAsthma', 'HadSkinCancer', 
    'HadCOPD', 'HadDepressiveDisorder', 'HadKidneyDisease', 'HadArthritis', 'HadDiabetes',
    'DeafOrHardOfHearing', 'BlindOrVisionDifficulty', 'DifficultyConcentrating', 'DifficultyWalking', 
    'DifficultyDressingBathing', 'DifficultyErrands', 'AlcoholDrinkers', 'ChestScan', 'HIVTesting',
    'FluVaxLast12', 'PneumoVaxEver', 'HighRiskLastYear', 'CovidPos'
]

# Convert specified columns to integers
for column in convert_list:
    hd_df[column] = hd_df[column].astype(int)

# Check the data types of the specified columns
hd_df[convert_list].dtypes

PhysicalHealthDays           int32
MentalHealthDays             int32
SleepHours                   int32
PhysicalActivities           int32
HadHeartAttack               int32
HadAngina                    int32
HadStroke                    int32
HadAsthma                    int32
HadSkinCancer                int32
HadCOPD                      int32
HadDepressiveDisorder        int32
HadKidneyDisease             int32
HadArthritis                 int32
HadDiabetes                  int32
DeafOrHardOfHearing          int32
BlindOrVisionDifficulty      int32
DifficultyConcentrating      int32
DifficultyWalking            int32
DifficultyDressingBathing    int32
DifficultyErrands            int32
AlcoholDrinkers              int32
ChestScan                    int32
HIVTesting                   int32
FluVaxLast12                 int32
PneumoVaxEver                int32
HighRiskLastYear             int32
CovidPos                     int32
dtype: object

In [18]:
# Confirm datatypes for the hd_df columns
hd_df.dtypes

State                         object
Sex                           object
GeneralHealth                 object
PhysicalHealthDays             int32
MentalHealthDays               int32
LastCheckupTime               object
PhysicalActivities             int32
SleepHours                     int32
RemovedTeeth                  object
HadHeartAttack                 int32
HadAngina                      int32
HadStroke                      int32
HadAsthma                      int32
HadSkinCancer                  int32
HadCOPD                        int32
HadDepressiveDisorder          int32
HadKidneyDisease               int32
HadArthritis                   int32
HadDiabetes                    int32
DeafOrHardOfHearing            int32
BlindOrVisionDifficulty        int32
DifficultyConcentrating        int32
DifficultyWalking              int32
DifficultyDressingBathing      int32
DifficultyErrands              int32
SmokerStatus                  object
ECigaretteUsage               object
ChestScan                      int32
AgeCategory                   object
HeightInMeters               float64
WeightInKilograms            float64
BMI                          float64
AlcoholDrinkers                int32
HIVTesting                     int32
FluVaxLast12                   int32
PneumoVaxEver                  int32
TetanusLast10Tdap             object
HighRiskLastYear               int32
CovidPos                       int32
Race                          object
Ethnicity                     object
dtype: object

In [19]:
# Reorder the dataframe (demographic data, anthropometric measurements, health status, chronic health conditions, disability/impairments, lifestyle factors, immunization, and medical/screening)
hd_df = hd_df[['State', 'Sex', 'AgeCategory', 'Race', 'Ethnicity',
               'HeightInMeters', 'WeightInKilograms', 'BMI',
               'GeneralHealth', 'PhysicalHealthDays', 'MentalHealthDays', 'PhysicalActivities', 'SleepHours', 
               'HadHeartAttack', 'HadAngina', 'HadStroke', 'HadAsthma', 'HadSkinCancer', 'HadCOPD', 'HadDepressiveDisorder', 'HadKidneyDisease', 'HadArthritis', 'HadDiabetes', 
               'DeafOrHardOfHearing', 'BlindOrVisionDifficulty', 'DifficultyConcentrating', 'DifficultyWalking', 'DifficultyDressingBathing', 'DifficultyErrands', 
               'SmokerStatus', 'ECigaretteUsage', 'AlcoholDrinkers',
               'LastCheckupTime', 'ChestScan','HIVTesting', 
               'FluVaxLast12', 'PneumoVaxEver', 'TetanusLast10Tdap',
               'RemovedTeeth', 'HighRiskLastYear', 'CovidPos',]]

pd.set_option('display.max_columns', 41) 
hd_df.head()

,State,Sex,AgeCategory,Race,Ethnicity,HeightInMeters,WeightInKilograms,BMI,GeneralHealth,PhysicalHealthDays,MentalHealthDays,PhysicalActivities,SleepHours,HadHeartAttack,HadAngina,HadStroke,HadAsthma,HadSkinCancer,HadCOPD,HadDepressiveDisorder,HadKidneyDisease,HadArthritis,HadDiabetes,DeafOrHardOfHearing,BlindOrVisionDifficulty,DifficultyConcentrating,DifficultyWalking,DifficultyDressingBathing,DifficultyErrands,SmokerStatus,ECigaretteUsage,AlcoholDrinkers,LastCheckupTime,ChestScan,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,RemovedTeeth,HighRiskLastYear,CovidPos
0,Alabama,Female,Age 65 to 69,White only,Non-Hispanic,1.60,71.67,27.99,Very good,4,0,1,9,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,Former smoker,Never used e-cigarettes in my entire life,0,Within past year (anytime less than 12 months ...,0,0,1,1,"Yes, received Tdap",None of them,0,0
1,Alabama,Male,Age 70 to 74,White only,Non-Hispanic,1.78,95.25,30.13,Very good,0,0,1,6,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,Former smoker,Never used e-cigarettes in my entire life,0,Within past year (anytime less than 12 months ...,0,0,1,1,"Yes, received tetanus shot but not sure what type",None of them,0,0
2,Alabama,Male,Age 75 to 79,White only,Non-Hispanic,1.85,108.86,31.66,Very good,0,0,0,8,0,0,0,0,0,0,0,0,1,0,0,1,0,1,0,0,Former smoker,Never used e-cigarettes in my entire life,1,Within past year (anytime less than 12 months ...,1,0,0,1,"No, did not receive any tetanus shot in the pa...","6 or more, but not all",0,1
3,Alabama,Female,Age 80 or older,White only,Non-Hispanic,1.70,90.72,31.32,Fair,5,0,1,9,0,0,0,0,1,0,1,0,1,0,0,0,0,1,0,0,Never smoked,Never used e-cigarettes in my entire life,0,Within past year (anytime less than 12 months ...,0,0,1,1,"No, did not receive any tetanus shot in the pa...",None of them,0,1
4,Alabama,Female,Age 80 or older,White only,Non-Hispanic,1.55,79.38,33.07,Good,3,15,1,5,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,Never smoked,Never used e-cigarettes in my entire life,0,Within past year (anytime less than 12 months ...,0,0,1,1,"No, did not receive any tetanus shot in the pa...",1 to 5,0,0

##### Transforming the Census Data Population Estimates (Age 18+)

In [20]:
# Set number of rows to be displayed
pd.set_option('display.max_rows', 68)

# Make a copy of the population estimates dataset
census_df = census_data_2022_df.copy()
census_df

,0,1,2,3
0,table with row headers in column A and column ...,NaN,NaN,NaN
1,Estimates of the Total Resident Population and...,NaN,NaN,NaN
2,Geographic Area,Total Resident\nPopulation,Resident Population Age 18\n Years and Older,NaN
3,NaN,NaN,Number,Percent
4,United States,333287557,260836730,78.3
5,Northeast,57040406,45544589,79.8
6,Midwest,68787595,53626659,78
7,South,128716192,100098310,77.8
8,West,78743364,61567172,78.2
9,.Alabama,5074296,3962734,78.1
10,.Alaska,733583,557060,75.9
11,.Arizona,7359197,5770187,78.4
12,.Arkansas,3045637,2348518,77.1
13,.California,39029342,30523315,78.2
14,.Colorado,5839926,4624351,79.2
15,.Connecticut,3626205,2895175,79.8
16,.Delaware,1018396,810269,79.6
17,.District of Columbia,671803,547328,81.5
18,.Florida,22244823,17948469,80.7
19,.Georgia,10912876,8402753,77
20,.Hawaii,1440196,1142870,79.4
21,.Idaho,1939033,1475629,76.1
22,.Illinois,12582032,9861901,78.4
23,.Indiana,6833037,5263114,77
24,.Iowa,3200517,2476028,77.4
25,.Kansas,2937150,2246318,76.5
26,.Kentucky,4512310,3507735,77.7
27,.Louisiana,4590241,3528548,76.9
28,.Maine,1385340,1137442,82.1
29,.Maryland,6164660,4818071,78.2
30,.Massachusetts,6981974,5644540,80.8
31,.Michigan,10034113,7924418,79
32,.Minnesota,5717184,4423022,77.4
33,.Mississippi,2940057,2261996,76.9
34,.Missouri,6177957,4813049,77.9
35,.Montana,1122867,889114,79.2
36,.Nebraska,1967923,1491246,75.8
37,.Nevada,3177772,2487994,78.3
38,.New Hampshire,1395231,1142307,81.9
39,.New Jersey,9261699,7267590,78.5
40,.New Mexico,2113344,1653831,78.3
41,.New York,19677151,15687863,79.7
42,.North Carolina,10698973,8404094,78.6
43,.North Dakota,779261,596486,76.5
44,.Ohio,11756058,9193508,78.2
45,.Oklahoma,4019800,3066654,76.3
46,.Oregon,4240137,3403149,80.3
47,.Pennsylvania,12972008,10347543,79.8
48,.Rhode Island,1093734,889822,81.4
49,.South Carolina,5282634,4164762,78.8
50,.South Dakota,909824,690659,75.9
51,.Tennessee,7051339,5513202,78.2
52,.Texas,30029572,22573234,75.2
53,.Utah,3380800,2449192,72.4
54,.Vermont,647064,532307,82.3
55,.Virginia,8683619,6816709,78.5
56,.Washington,7785786,6139213,78.9
57,.West Virginia,1775156,1423234,80.2
58,.Wisconsin,5892539,4646910,78.9
59,.Wyoming,581381,451267,77.6
60,NaN,NaN,NaN,NaN
61,Puerto Rico,3221789,2703450,83.9
62,Note: The estimates are developed from a base ...,NaN,NaN,NaN
63,Suggested Citation:,NaN,NaN,NaN
64,Estimates of the Total Resident Population and...,NaN,NaN,NaN
65,"Source: U.S. Census Bureau, Population Division",NaN,NaN,NaN
66,Release Date: December 2022,NaN,NaN,NaN

In [21]:
# Rename the census_df columns
census_df.rename(columns = {
    0: 'State', 
    1: 'TotalPop', 
    2: 'TotalNum', 
    3: 'TotalPercent', 
}, inplace=True)

census_df.head(10)

,State,TotalPop,TotalNum,TotalPercent
0,table with row headers in column A and column ...,NaN,NaN,NaN
1,Estimates of the Total Resident Population and...,NaN,NaN,NaN
2,Geographic Area,Total Resident\nPopulation,Resident Population Age 18\n Years and Older,NaN
3,NaN,NaN,Number,Percent
4,United States,333287557,260836730,78.3
5,Northeast,57040406,45544589,79.8
6,Midwest,68787595,53626659,78
7,South,128716192,100098310,77.8
8,West,78743364,61567172,78.2
9,.Alabama,5074296,3962734,78.1

In [22]:
# Drop Nan values from the population estimates (contain descriptions of the dataset)
census_df.dropna(inplace=True)
census_df.head(10)

            State   TotalPop   TotalNum TotalPercent
4   United States  333287557  260836730         78.3
5       Northeast   57040406   45544589         79.8
6         Midwest   68787595   53626659           78
7           South  128716192  100098310         77.8
8            West   78743364   61567172         78.2
9        .Alabama    5074296    3962734         78.1
10        .Alaska     733583     557060         75.9
11       .Arizona    7359197    5770187         78.4
12      .Arkansas    3045637    2348518         77.1
13    .California   39029342   30523315         78.2

In [23]:
# Dropping rows (to keep all states and the District of Columbia ONLY)
us_states_df = census_df[~census_df['State'].isin(['United States', 'Northeast', 'Midwest', 'South', 'West', 'Puerto Rico'])].reset_index(drop=True)
us_states_df.head()

         State  TotalPop  TotalNum TotalPercent
0     .Alabama   5074296   3962734         78.1
1      .Alaska    733583    557060         75.9
2     .Arizona   7359197   5770187         78.4
3    .Arkansas   3045637   2348518         77.1
4  .California  39029342  30523315         78.2

In [24]:
us_states_df['State'] = us_states_df['State'].replace(r'^\.', '', regex=True)
us_states_df.head(10)

                  State  TotalPop  TotalNum TotalPercent
0               Alabama   5074296   3962734         78.1
1                Alaska    733583    557060         75.9
2               Arizona   7359197   5770187         78.4
3              Arkansas   3045637   2348518         77.1
4            California  39029342  30523315         78.2
5              Colorado   5839926   4624351         79.2
6           Connecticut   3626205   2895175         79.8
7              Delaware   1018396    810269         79.6
8  District of Columbia    671803    547328         81.5
9               Florida  22244823  17948469         80.7

In [25]:
# Check the dataypes
us_states_df.dtypes

State           object
TotalPop        object
TotalNum        object
TotalPercent    object
dtype: object

In [26]:
# Convert the Total Population and Number columns to 'integer' and Total Percentage column to a `float` data type.
us_states_df = us_states_df.astype({'TotalPop': 'int', 'TotalNum': 'int', 'TotalPercent': 'float'})
us_states_df.head()

        State  TotalPop  TotalNum  TotalPercent
0     Alabama   5074296   3962734          78.1
1      Alaska    733583    557060          75.9
2     Arizona   7359197   5770187          78.4
3    Arkansas   3045637   2348518          77.1
4  California  39029342  30523315          78.2

In [27]:
# Confirm the dataypes
us_states_df.dtypes

State            object
TotalPop          int32
TotalNum          int32
TotalPercent    float64
dtype: object

In [28]:
# Define regions
us_regions = {
    'Northeast': ['Connecticut', 'Maine', 'Massachusetts', 'New Hampshire', 'Rhode Island', 'Vermont', 'New Jersey', 'New York', 'Pennsylvania'],
    'Midwest': ['Illinois', 'Indiana', 'Michigan', 'Ohio', 'Wisconsin', 'Iowa', 'Kansas', 'Minnesota', 'Missouri', 'Nebraska', 'North Dakota', 'South Dakota'],
    'South': ['Delaware', 'District of Columbia', 'Florida', 'Georgia', 'Maryland', 'North Carolina', 'South Carolina', 'Virginia', 'West Virginia', 'Alabama', 'Kentucky', 'Mississippi', 'Tennessee', 'Arkansas', 'Louisiana', 'Oklahoma', 'Texas'],
    'West': ['Arizona', 'Colorado', 'Idaho', 'Montana', 'Nevada', 'New Mexico', 'Utah', 'Wyoming', 'Alaska', 'California', 'Hawaii', 'Oregon', 'Washington']
}

# Create a new 'Region' column based on the states
def assign_region(state):
    if state in us_regions['Northeast']:
        return 'Northeast'
    elif state in us_regions['Midwest']:
        return 'Midwest'
    elif state in us_regions['South']:
        return 'South'
    elif state in us_regions['West']:
        return 'West'
    else:
        return 'Other'

# Assuming usa_states_df is your DataFrame containing the USA states
census_df = pd.DataFrame(us_states_df)
census_df['Region'] = census_df['State'].apply(assign_region)

# Create a new DataFrame for the 'Regions' table
us_regions_df = census_df[['Region', 'State', 'TotalPop', 'TotalNum','TotalPercent']]
us_regions_df

       Region                 State  TotalPop  TotalNum  TotalPercent
0       South               Alabama   5074296   3962734          78.1
1        West                Alaska    733583    557060          75.9
2        West               Arizona   7359197   5770187          78.4
3       South              Arkansas   3045637   2348518          77.1
4        West            California  39029342  30523315          78.2
5        West              Colorado   5839926   4624351          79.2
6   Northeast           Connecticut   3626205   2895175          79.8
7       South              Delaware   1018396    810269          79.6
8       South  District of Columbia    671803    547328          81.5
9       South               Florida  22244823  17948469          80.7
10      South               Georgia  10912876   8402753          77.0
11       West                Hawaii   1440196   1142870          79.4
12       West                 Idaho   1939033   1475629          76.1
13    Midwest              Illinois  12582032   9861901          78.4
14    Midwest               Indiana   6833037   5263114          77.0
15    Midwest                  Iowa   3200517   2476028          77.4
16    Midwest                Kansas   2937150   2246318          76.5
17      South              Kentucky   4512310   3507735          77.7
18      South             Louisiana   4590241   3528548          76.9
19  Northeast                 Maine   1385340   1137442          82.1
20      South              Maryland   6164660   4818071          78.2
21  Northeast         Massachusetts   6981974   5644540          80.8
22    Midwest              Michigan  10034113   7924418          79.0
23    Midwest             Minnesota   5717184   4423022          77.4
24      South           Mississippi   2940057   2261996          76.9
25    Midwest              Missouri   6177957   4813049          77.9
26       West               Montana   1122867    889114          79.2
27    Midwest              Nebraska   1967923   1491246          75.8
28       West                Nevada   3177772   2487994          78.3
29  Northeast         New Hampshire   1395231   1142307          81.9
30  Northeast            New Jersey   9261699   7267590          78.5
31       West            New Mexico   2113344   1653831          78.3
32  Northeast              New York  19677151  15687863          79.7
33      South        North Carolina  10698973   8404094          78.6
34    Midwest          North Dakota    779261    596486          76.5
35    Midwest                  Ohio  11756058   9193508          78.2
36      South              Oklahoma   4019800   3066654          76.3
37       West                Oregon   4240137   3403149          80.3
38  Northeast          Pennsylvania  12972008  10347543          79.8
39  Northeast          Rhode Island   1093734    889822          81.4
40      South        South Carolina   5282634   4164762          78.8
41    Midwest          South Dakota    909824    690659          75.9
42      South             Tennessee   7051339   5513202          78.2
43      South                 Texas  30029572  22573234          75.2
44       West                  Utah   3380800   2449192          72.4
45  Northeast               Vermont    647064    532307          82.3
46      South              Virginia   8683619   6816709          78.5
47       West            Washington   7785786   6139213          78.9
48      South         West Virginia   1775156   1423234          80.2
49    Midwest             Wisconsin   5892539   4646910          78.9
50       West               Wyoming    581381    451267          77.6

In [29]:
# Export hd_df and us_regions_df as CSV files
hd_df.to_csv("Resource/hd_df.csv", index=False)
us_regions_df.to_csv("Resource/us_regions_census.csv", index=False)